-- Generated from /home/seth/repos/personal/tintin-rots/bot/areas/*.tt.
-- Mob text is matched exactly; attack is the TinTin++ mobname.
bot_areas = {
  ancient = { title = "Ancient Spider",
    commands = {},
    mob_triggers = {
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "spider" },
      { text = "A dark spider glares evilly at you.", attack = "spider" },
      { text = "An enormous, swollen spider watches over her lair.", attack = "spider" },
      { text = "A shadowy spider sits content and bloated after its meal.", attack = "spider" },
      { text = "A large, black spider watches you with evil in its many eyes.", attack = "spider" },
      { text = "The Ancient Spider is here, sucking the life from its latest victim.", attack = "Ancient", hard = true },
    },
  },
  blinds = { title = "Blind Spiders",
    commands = {"n", "e", "w", "s", "e", "e", "e", "e", "n", "s", "w", "w", "s", "s", "w", "s", "w", "s", "n", "e", "n", "e", "e", "e", "n", "od e", "e", "od s", "e", "e", "n", "od n"},
    mob_triggers = {
      { text = "A blind spider hangs from a web here.", attack = "blind", hard = true },
      { text = "A shadowy spider sneaks through the darkness. (hiding)", attack = "shadowy" },
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "malicious" },
      { text = "A large hairy spider is here, looking all around.", attack = "spider" },
    },
  },
  bone = { title = "Bone Structure",
    commands = {"s", "s", "w", "n", "w", "e", "n", "n", "s", "w", "w", "e", "e", "s", "s", "e", "s", "n", "e", "n", "e", "w", "n", "n", "s", "e", "e", "od s", "od d", "n", "n", "e", "e", "s", "w", "e", "e", "n", "e", "e", "w", "w", "s", "w", "w", "e", "s", "w", "e", "e", "s", "e", "n", "n", "s", "e", "od s", "od d", "s", "e", "e", "w", "w", "s", "e", "w", "s", "e", "e", "w", "w", "s", "n", "n", "w", "s", "s", "n", "n", "n", "n", "s", "w", "s", "w", "s", "od e", "od d", "n", "e", "e", "e", "e", "s", "n", "w", "w", "s", "s", "e", "n", "s", "w", "w", "n", "s", "e", "s", "e", "s", "n", "w", "w", "s", "n", "e", "s", "od s", "od d", "s", "s", "s", "w", "n", "n", "n", "w", "e", "s", "s", "w", "n", "s", "s", "n", "e", "s", "e", "n", "n", "e", "s", "s", "e", "w", "n", "n", "e", "n", "w", "od d", "w", "n", "w", "e", "n", "s", "e", "n", "n", "e", "e", "s", "w", "s", "e", "s", "n", "w", "n", "e", "e", "s", "e", "w", "s", "n", "n", "w", "n", "w", "w", "s", "s", "s", "od u", "e", "s", "w", "w", "n", "od u", "od n", "n", "n", "n", "n", "w", "w", "s", "od u", "od w", "n", "e", "n", "e", "s", "e", "n", "n", "od u", "od n", "w", "s", "w", "n", "w", "n", "n", "w", "w", "s", "s", "od u", "od n", "w", "w", "s", "s", "w", "n", "n", "od u"},
    mob_triggers = {
      { text = "A cave troll is standing here, pounding his two huge fists together.", attack = "cave" },
      { text = "A large grey troll grumbles ominously here.", attack = "troll" },
      { text = "A brown, angry-looking bear is padding around here.", attack = "bear" },
      { text = "A gigantic crystalline worm emerges from the dark soil.", attack = "worm" },
      { text = "A dark-haired bear prowls around here.", attack = "bear" },
      { text = "A massive crystalline crawler stalks around in search of food.", attack = "crawler" },
      { text = "A huge tiger beetle stands here drooling at the mouth.", attack = "beetle" },
      { text = "A large black snake is coiled up here, gazing at you intently.", attack = "snake" },
      { text = "A large white scorpion carefully searches the area as it tracks its prey.", attack = "scorpion", hard = true },
      { text = "A massive silvery toad stares at you with hunger in its eyes.", attack = "toad" },
      { text = "A gigantic, black orcish warrior patrols the tunnels here.", attack = "gigantic" },
      { text = "A huge, bulky troll sits in the corner, slowly eating an old corpse.", attack = "bulky", hard = true },
      { text = "A massive crystalline spider stands here, chattering its teeth. (hiding)", attack = "crystalline" },
      { text = "A massive crystalline spider stands here, chattering its teeth.", attack = "crystalline" },
    },
  },
  breeders = { title = "Warg Breeders", start_room = "10450",
    commands = {"s", "w", "ride", "w", "s", "w", "e", "e", "e", "e", "e", "w", "n", "s", "s", "n", "w", "w", "w", "e", "n", "s", "s", "n", "e", "s", "s", "s", "e", "n", "n", "n", "w", "w", "n", "e", "dismount", "e", "n", "od w"},
    mob_triggers = {
      { text = "A ferocious warg stands here, snarling maliciously.", attack = "ferocious" },
      { text = "A trained warg waits here for an order from its masters.", attack = "trained" },
      { text = "An evil, black warg paces around the clearing.", attack = "evil" },
      { text = "A thin warg crouches here cautiously.", attack = "thin" },
      { text = "The master breeder stands here with whip in hand.", attack = "master" },
    },
  },
  ["cavetrolls-lhuth"] = { title = "Cave Trolls - Lhuth Area", start_room = "2345",
    commands = {"od w", "s", "s", "w", "od u", "s", "s", "w", "w", "n", "n", "e", "n", "e", "s", "od d", "e", "n", "n", "od e"},
    mob_triggers = {
      { text = "A big humanoid figure all covered with mud is here.", attack = "troll" },
      { text = "A large wild troll is here, green skinned and angry.", attack = "troll" },
      { text = "A hunched forest troll moves around here, arms dragging on the ground.", attack = "troll" },
    },
  },
  durgurth = { title = "Durgurth Keep",
    commands = {"dismount", "s", "e", "w", "w", "e", "s", "e", "s", "s", "n", "n", "w", "w", "s", "s", "d", "e", "n", "n", "n", "n", "s", "s", "s", "s", "d", "e", "w", "w", "e", "n", "n", "d", "w", "n", "w", "s", "s", "e", "e", "w", "s", "e", "s", "e", "w", "n", "w", "d", "e", "e", "e", "e", "e", "w", "w", "w", "w", "w", "u", "n", "u", "e", "n", "u", "w", "u", "n", "e", "s", "u", "n", "#5 pick oak", "n", "s", "s", "d", "n", "n", "n", "n", "ride"},
    mob_triggers = {
      { text = "A hardened wraith hovers here.", attack = "wraith" },
      { text = "A heavy suit of armour stands here wielding a broadsword.", attack = "suit" },
      { text = "A carangoroth lurches towards you.", attack = "carangoroth" },
    },
  },
  ep = { title = "Enchanted Path", start_room = "3810", cycle = true,
    commands = {"n", "e", "n", "dismount", "n", "n", "e", "d", "w", "e", "e", "e", "e", "e", "e", "e", "u", "e", "e", "s", "s", "w", "n", "w", "s", "s", "ride", "w", "n", "w", "w", "w", "w", "w", "w", "s", "e", "e", "e", "e", "s", "w", "w", "w", "w", "s", "e", "e", "e", "e", "e", "e", "n", "e", "e", "e", "e", "n", "e", "n", "w", "n", "n", "e", "e", "e", "e", "e", "s", "w", "w", "w", "e", "w", "w", "e", "s", "e", "s", "e", "n", "e", "s", "n", "e", "e", "e", "n", "w", "n", "w", "e", "e", "e", "e", "e", "e", "e", "s", "w", "w", "w", "w", "s", "e", "e", "e", "e", "e", "e", "e", "n", "w", "w", "n", "e", "e", "e", "e", "e", "s", "w", "w", "w", "s", "e", "e", "e", "e", "n", "n", "s", "s", "s", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "s", "dismount", "w", "n", "s", "e", "ride", "e", "e", "e", "e", "e", "s", "e", "s", "w", "s", "dismount", "w", "w", "w", "ride", "n", "e", "e", "w", "w", "s", "s", "s", "s", "s", "s", "s", "s", "s", "e", "e", "s", "w", "w", "s", "s", "s", "e", "n", "n", "n", "e", "n", "w", "n", "n", "e", "e", "e", "s", "w", "w", "w", "s", "e", "s", "s", "s", "s", "e", "n", "n", "n", "e", "s", "s", "s", "e", "n", "n", "n", "e", "n", "w", "n", "n", "n", "w", "w", "n", "e", "e", "e", "s", "n", "e", "n", "n", "w", "s", "w", "n", "n", "n", "e", "s", "e", "e", "e", "s", "w", "s", "s", "w", "s", "e", "s", "w", "w", "s", "e", "e", "e", "s", "w", "w", "w", "s", "e", "e", "e", "s", "w", "w", "w", "w", "s", "s", "s", "e", "e", "n", "w", "e", "n", "w", "e", "e", "s", "s", "e", "s", "w", "w", "e", "s", "s", "e", "n", "n", "n", "n", "w", "n", "e", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "w", "n", "w", "n", "e", "e", "s", "n", "n", "e", "n", "e", "e", "e", "e", "n", "w", "n", "n", "e", "s", "s", "e", "e", "n", "w", "n", "e", "e", "s", "n", "e", "s", "e", "n", "w", "w", "w", "s", "s", "e", "e", "e", "e", "e", "e", "n", "w", "w", "n", "e", "e", "e", "e", "e", "e", "e", "e", "e", "s", "s", "w", "w", "e", "s", "e", "w", "n", "e", "n", "w", "w", "w", "w", "w", "w", "e", "s", "e", "e", "w", "w", "w", "s", "w", "w", "w", "w", "s", "e", "e", "e", "e", "w", "w", "w", "w", "w", "w", "n", "e", "w", "w", "w", "w", "s", "e", "e", "w", "w", "w", "w", "w", "dismount", "ride", "e", "dismount", "s", "w", "w", "s", "s", "e", "e", "n", "w", "n", "e", "n", "ride", "e", "s", "e", "s", "e", "e", "s", "s", "w", "w", "w", "w", "w", "w", "s", "s", "s", "s", "s", "s", "s", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "w", "w", "n", "e", "e", "e", "e", "e", "e", "w", "w", "w", "w", "w", "w", "w", "n", "e", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "w", "w", "w", "n", "n", "n", "e", "s", "s", "n", "e", "s", "n", "n", "e", "s", "s", "n", "e", "s", "n", "n", "e", "s", "e", "e", "n", "w", "n", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "w", "n", "s", "w", "w", "n", "w", "w", "w", "s", "e", "e", "s", "w", "s", "w", "w", "w", "w", "s", "s", "w", "w", "s", "e", "e", "e", "e", "e", "e", "s", "w", "w", "w", "s", "s", "w", "dismount", "s", "n", "ride", "e", "s", "e", "e", "e", "e", "e", "n", "w", "w", "n", "w", "s", "w", "s", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "w", "n", "w", "w", "e", "n", "e", "n", "s", "e", "n", "n", "n", "n", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "s", "e", "s", "e", "e", "s", "w", "w", "w", "n", "s", "s", "w", "s", "e", "w", "w", "n", "w", "w", "w", "n", "n", "e", "n", "w", "w", "w", "s", "w", "w", "s", "e", "e", "s", "w", "w", "e", "e", "e", "s", "s", "s", "e", "e", "e", "e", "n", "e", "s", "e", "e", "e", "e", "w", "n", "w", "w", "w", "w", "n", "w", "w", "s", "e", "w", "w", "w", "n", "n", "e", "e", "e", "e", "s", "e", "e", "n", "e", "e", "e", "e", "e", "n", "n", "n", "n", "w", "e", "e", "s", "n", "e", "w", "s", "s", "s", "s", "s", "s", "w", "n", "s", "e", "s", "w", "s", "s", "s", "e", "n", "n", "n", "n", "e", "s", "e", "s", "w", "s", "s", "e", "n", "s", "w", "s", "w", "w", "s", "e", "e", "e", "n", "w", "n", "n", "n", "e", "n", "e", "s", "s", "s", "e", "e", "e", "e", "e", "n", "w", "w", "w", "w", "w", "n", "e", "e", "e", "e", "e", "e", "s", "e", "e", "s", "s", "s", "s", "w", "w", "s", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "n", "w", "s", "w", "n", "w", "s", "w", "n", "s", "w", "w", "w", "n", "n", "n", "e", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "w", "w", "n", "w", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "e", "e", "n", "n", "n", "w", "dismount", "s", "w", "n", "s", "ride", "w", "w", "s", "w", "n", "w", "s", "w", "n", "w", "w", "s", "s", "w", "n", "n", "w", "dismount", "n", "u", "w", "w", "n", "s", "s", "n", "w", "n", "s", "s", "u", "e", "d", "n", "e", "e", "d", "s", "ride", "w", "w", "n", "e", "n", "w", "w", "n", "e", "e", "dismount", "e", "n", "n", "e", "e", "s", "s", "w", "n", "w", "s", "w", "ride", "n", "n", "w", "s", "w", "s", "s", "e", "e", "e", "e", "e", "s", "w", "n", "e", "e", "n", "e", "n", "w", "e", "n", "w", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "s", "w", "w", "w", "w", "w", "w", "w", "w", "s", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "w", "n", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "n", "n", "dismount", "n", "u", "d", "e", "ride", "s", "s", "s", "s", "s", "w", "w", "w", "w", "w", "w", "s", "w", "n", "w", "s", "w", "n", "w", "w", "w", "w", "w", "w", "s", "s", "s", "e", "n", "e", "n", "w", "e", "e", "e", "e", "e", "e", "e", "s", "e", "e", "e", "n", "e", "e", "s", "s", "w", "w", "w", "s", "w", "n", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "s", "w", "n", "w", "w", "s", "e", "e", "e", "e", "e", "s", "w", "w", "e", "s", "w", "w", "n", "n", "w", "s", "s", "e", "e", "e", "e", "e", "e", "e", "n", "e", "n", "w", "n", "w", "w", "dismount", "s", "s", "e", "n", "w", "n", "ride", "e", "e", "e", "s", "e", "s", "e", "e", "n", "e", "s", "e", "n", "n", "e", "s", "s", "e", "n", "e", "s", "s", "e", "n", "n", "e", "s", "s", "w", "w", "w", "w", "s", "e", "e", "e", "e", "s", "w", "w", "w", "w", "s", "e", "e", "e", "e", "w", "s", "w", "w", "e"},
    mob_triggers = {
      { text = "A large grizzly bear with golden fur stands here.", attack = "golden" },
      { text = "A large black bear is standing here.", attack = "bear" },
      { text = "A large white bear wanders through the area.", attack = "bear" },
      { text = "An agile wolf, cloaked with red fur, walks through here.", attack = "red" },
      { text = "A brown, angry-looking bear is padding around here.", attack = "angry" },
      { text = "A long, purplish vine lies on the ground. (hiding)", attack = "vine" },
      { text = "A large buck is here, rutting against the trees.", attack = "buck" },
      { text = "A huge wolf stares at you intently.", attack = "huge" },
      { text = "A black wolf looks at you and begins to growl.", attack = "black" },
      { text = "A large hairy coyote growls furiously and foams at the mouth.", attack = "coyote" },
      { text = "A large grey-haired wolf stands here with fangs bared.", attack = "dire" },
      { text = "A thin wild dog is here, glaring at you from the shadows.", attack = "dog" },
      { text = "A grey wolf is growling at you.", attack = "grey" },
      { text = "A black wolf wanders about, growling and frothing at the mouth.", attack = "wolf" },
      { text = "A dark-haired bear prowls around here.", attack = "bear" },
      { text = "A large wild dog watches you carefully.", attack = "dog" },
      { text = "A brown bear rests here on its haunches.", attack = "bear" },
      { text = "A large, brown bear is here, sleeping.", attack = "bear" },
      { text = "A white wolf lurks here, beautiful, yet deadly.", attack = "wolf" },
      { text = "A fetid black fungus grows here, covering the ground.", attack = "fungus" },
      { text = "A giant bat looms overhead.", attack = "bat" },
      { text = "A grey bat flies silently through the air.", attack = "bat" },
      { text = "A dark spider glares evilly at you.", attack = "spider" },
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "spider" },
      { text = "A large snake with a flattened tail moves swiftly through the water here.", attack = "snake" },
      { text = "A black willow tree looms here, its branches swaying back and forth.", attack = "willow", hard = true },
      { text = "A red furred wolf is standing here.", attack = "wolf" },
      { text = "A huge wild boar with bristly spines and huge tusks snorts and stamps.", attack = "boar" },
      { text = "A brown wolverine walks through here, leering around him with malicious intent.", attack = "wolverine" },
      { text = "A dark, black spider hangs down from a web, glaring at you evilly.", attack = "widow" },
      { text = "A spider hangs in the webs here, nursing her hatchlings.", attack = "spider" },
      { text = "A large, dark brown moose is here, chewing on a shrub.", attack = "moose" },
      { text = "A large wild cow is standing here, munching on some grass.", attack = "cow" },
    },
  },
  fungus = { title = "Honey Fungus",
    commands = {},
    mob_triggers = {
      { text = "A honey fungus has spread through the clearing, covering the trees and ground.", attack = "fungus" },
    },
  },
  matron = { title = "Troll Matron",
    commands = {"e", "d", "s", "w", "e", "n", "u", "w", "w", "d", "w", "e", "u", "e", "ride", "n"},
    mob_triggers = {
      { text = "A stony-fisted troll lumbers about here.", attack = "troll" },
      { text = "A massive grey spider rests its bloated body here", attack = "spider" },
    },
  },
  mirkwoods = { title = "Mirkwoods",
    commands = {},
    mob_triggers = {
      { text = "A massive mirkwolf stares at you through blood red eyes.", attack = "massive" },
      { text = "A cave troll is standing here, pounding his two huge fists together.", attack = "troll" },
      { text = "A huge mirkwolf tenses its massive frame in readiness.", attack = "huge" },
      { text = "A hunched forest troll moves around here, arms dragging on the ground.", attack = "troll" },
      { text = "An evil, black warg paces around the clearing.", attack = "evil" },
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "spider" },
      { text = "A trained warg waits here for an order from its master.", attack = "trained" },
      { text = "A large grizzly bear with golden fur stands here.", attack = "golden" },
      { text = "A blind spider hangs from a web here.", attack = "blind", hard = true },
      { text = "A spry spider weaves the cobwebs together as it scurries around the chamber.", attack = "spider" },
      { text = "A goblin hunter stands next to his kill, spear in hand.", attack = "goblin" },
      { text = "A trained warg waits here for an order from its masters.", attack = "trained" },
      { text = "A breeder assistant stands here trying to look busy.", attack = "breeder" },
      { text = "A twisted black spider is here waiting for dinner.", attack = "spider" },
    },
  },
  ["mor-erlond"] = { title = "Mor Erlond", start_room = "8836", cycle = true,
    commands = {"n", "n", "n", "n", "n", "n", "w", "w", "_reveal_command", "w", "_reveal_command", "w", "_reveal_command", "w", "_reveal_command", "w", "_reveal_command", "n", "_reveal_command", "w", "_reveal_command", "s", "n", "e", "s", "e", "n", "_reveal_command", "n", "_reveal_command", "w", "_reveal_command", "n", "_reveal_command", "n", "_reveal_command", "w", "_reveal_command", "s", "_reveal_command", "s", "n", "n", "e", "dismount", "e", "_reveal_command", "s", "ride", "e", "_reveal_command", "n", "e", "_reveal_command", "s", "dismount", "e", "_reveal_command", "s", "e", "ride", "n", "e", "e", "n", "n", "dismount", "n", "e", "ride", "n", "n", "e", "dismount", "e", "e", "n", "ride", "n", "e", "n", "n", "n", "n", "n", "n", "n", "n", "e", "n", "e", "e", "e", "e", "e", "e", "e", "n", "n", "n", "n", "n", "od e", "e", "dismount", "e", "ride", "w", "w", "od w", "w", "n", "n", "e", "dismount", "n", "w", "ride", "n", "w", "w", "s", "s", "w", "n", "w", "w", "n", "e", "e", "n", "w", "n", "e", "n", "e", "dismount", "e", "w", "n", "s", "w", "w", "n", "n", "w", "w", "od w", "w", "n", "n", "ride", "w", "n", "e", "e", "dismount", "n", "e", "e", "n", "ride", "e", "dismount", "n", "s", "ride", "e", "dismount", "s", "s", "s", "s", "w", "od w", "n", "s", "od e", "e", "s", "e", "n", "e", "e", "ride", "n", "n", "n", "w", "w", "n", "n", "n", "e", "n", "e", "n", "e", "e", "n", "w", "n", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "s", "s", "e", "s", "w", "n", "n", "dismount", "od d", "dismount", "e", "n", "s", "e", "w", "w", "w", "s", "s", "e", "s", "n", "w", "n", "n", "e", "od u", "ride", "n", "n", "e", "e", "e", "e", "e", "e", "e", "e", "e", "e", "n", "w", "w", "w", "e", "n", "e", "w", "w", "w", "w", "w", "s", "e", "e", "w", "w", "w", "w", "w", "w", "n", "e", "e", "e", "n", "n", "w", "w", "w", "e", "e", "e", "s", "s", "e", "e", "e", "e", "e", "e", "e", "e", "s", "s", "s", "s", "s", "w", "s", "w", "s", "w", "s", "s", "s", "e", "e", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "e", "s", "s", "s", "s", "s", "w", "w", "w", "w", "w", "w", "w", "s", "w", "s", "s", "s", "s", "s", "s", "s", "s", "w", "w", "w", "s", "s", "w", "s", "s", "s", "w", "s", "s", "w", "w", "s", "s", "s", "e", "s", "s", "s", "s", "s", "e", "e", "e", "s", "s", "e", "s", "n", "w", "n", "n", "e", "n", "e", "e", "e", "e", "e", "n", "n", "e", "e", "e", "s", "e", "e", "n", "n", "n", "n", "n", "n", "n", "e", "dismount", "e", "d", "u", "w", "ride", "n", "e", "n", "n", "n", "n", "dismount", "e", "n", "w", "n", "e", "n", "w", "w", "n", "e", "ride", "n", "e", "n", "n", "dismount", "n", "e", "e", "ride", "s", "e", "dismount", "d", "e", "n", "w", "e", "n", "s", "s", "w", "u", "ride", "u", "u", "u", "u", "u"},
    mob_triggers = {
      { text = "A massive mirkwolf stares at you through blood red eyes.", attack = "massive" },
      { text = "A huge mirkwolf tenses its massive frame in readiness.", attack = "huge" },
      { text = "A hunched forest troll moves around here, arms dragging on the ground.", attack = "troll" },
      { text = "An evil, black warg paces around the clearing.", attack = "evil" },
      { text = "A dark lithe man is here, leaning against a tree.", attack = "man" },
      { text = "Perched in a tree, a grey and black speckled spider stares at you hungrily.", attack = "spider" },
      { text = "Perched in a tree, a grey and black speckled spider stares at you hungrily. (hiding)", attack = "spider" },
      { text = "A swelled black spider is busy spinning a cocoon in a nearby tree.", attack = "spider" },
      { text = "A large trapdoor spider lies here waiting for its next victim. (hiding)", attack = "spider" },
      { text = "A massive timberwolf bares its teeth as you approach.", attack = "timberwolf" },
      { text = "A grey speckled spider slides along the webs.", attack = "spider" },
      { text = "A grey speckled spider slides along the webs. (hiding)", attack = "spider" },
      { text = "Some twisted vines hang from the trees.", attack = "vines" },
      { text = "A black willow tree looms here, its branches swaying back and forth.", attack = "willow" },
      { text = "The mother bear is lying here, watching her cubs.", attack = "bear" },
      { text = "A huge bear prowls around guarding those in his care.", attack = "bear" },
      { text = "An angry mother troll stands here, protecting her brood.", attack = "troll" },
      { text = "A baby troll lies here, screaming loudly.", attack = "troll" },
      { text = "A large wild troll is here, green skinned and angry.", attack = "troll" },
      { text = "A giant bat looms overhead.", attack = "bat" },
      { text = "A large bear paces back and forth here.", attack = "bear" },
      { text = "A black wolf looks at you and begins to growl.", attack = "wolf" },
      { text = "A huge wolf stares at you intently.", attack = "huge" },
      { text = "A black wolf wanders about, growling and frothing at the mouth.", attack = "wolf" },
      { text = "A huge wild boar with bristly spines and huge tusks snorts and stamps.", attack = "boar" },
      { text = "A creeper from a huge plant snakes here towards any movement it senses.", attack = "plant" },
      { text = "An agitated tree seems to glare menacingly at you, waving its branches.", attack = "tree" },
      { text = "A hideous dark beast towers above you with hunger in its eyes.", attack = "beast" },
      { text = "The mother mirkwolf watches you intently.", attack = "mother" },
      { text = "A large mirkwolf stands here baring its teeth.", attack = "large" },
      { text = "A shadowy spider sneaks through the darkness. (hiding)", attack = "shadowy" },
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "malicious" },
      { text = "A shadowy spider sneaks through the darkness.", attack = "shadowy" },
      { text = "A grey wolf is growling at you.", attack = "grey" },
    },
  },
  ["old-ancient"] = { title = "Old Ancient Spider",
    commands = {"od d", "od w", "w", "s", "w", "d", "u", "e", "s", "w", "e", "n", "e", "s", "n", "e", "s", "od d", "e", "e", "u"},
    mob_triggers = {
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "malicious" },
      { text = "A shadowy spider sneaks through the darkness. (hiding)", attack = "shadowy" },
      { text = "A shadowy spider sneaks through the darkness.", attack = "shadowy" },
    },
  },
  semirkwood = { title = "Southeast Mirkwoods", start_room = "7470",
    commands = {"s", "s", "e", "s", "e", "e", "e", "s", "w", "w", "w", "s", "e", "e", "e", "s", "w", "s", "e", "w", "w", "w", "n", "s", "s", "e", "e", "w", "s", "w", "s", "n", "e", "s", "e", "n", "e", "n", "s", "s", "s", "w", "s", "n", "e", "s", "e", "e", "e", "e", "e", "s", "w", "w", "e", "s", "w", "s", "w", "e", "s", "s", "w", "e", "e", "n", "n", "e", "s", "e", "n", "s", "e", "n", "n", "w", "e", "e", "e", "s", "e", "e", "n", "w", "e", "s", "s", "w", "w", "w", "w", "s", "s", "w", "w", "s", "w", "w", "s", "s", "s", "n", "w", "s", "s", "s", "s", "e", "e", "n", "e", "s", "s", "w", "s", "e", "s", "w", "n", "w", "w", "s", "w", "n", "n", "n", "n", "open blackweb", "od w", "w", "n", "e", "e", "w", "s", "od e", "e", "n", "n", "n", "n", "n", "e", "e", "e", "n", "e", "e", "e", "n", "e", "s", "e", "n", "n", "e", "n", "e", "e", "e", "e", "n", "w", "w", "e", "e", "e", "e", "e", "e", "s", "w", "s", "s", "n", "e", "e", "s", "w", "s", "w", "w", "n", "w", "n", "s", "s", "n", "e", "s", "e", "e", "e", "e", "w", "n", "e", "n", "e", "n", "w", "n", "w", "n", "e", "n", "n", "e", "e", "e", "e", "e", "e", "s", "s", "e", "e", "w", "w", "s", "w", "n", "s", "e", "n", "n", "e", "e", "e", "n", "e", "n", "n", "e", "n", "w", "n", "e", "n", "e", "s", "s", "s", "e", "n", "e", "s", "s", "w", "w", "s", "e", "e", "s", "w", "w", "w", "s", "w", "e", "e", "s", "w", "w", "s", "e", "s", "e", "n", "e", "n", "n", "e", "e", "e", "e", "n", "w", "w", "w", "e", "e", "e", "s", "s", "w", "s", "w", "s", "s", "s", "n", "e", "n", "s", "e", "s", "n", "e", "n", "w", "n", "s", "e", "e", "e", "n", "e", "e", "s", "e", "s", "w", "e", "s", "e", "w", "n", "e", "n", "s", "e", "e", "s", "w", "e", "e", "w", "n", "e", "e", "e", "s", "n", "w", "w", "n", "w", "w", "e", "n", "w", "w", "w", "n", "w", "w", "n", "n", "n", "e", "w", "s", "s", "w", "w", "n", "w", "n", "e", "w", "w", "w", "e", "e", "s", "e", "s", "w", "e", "s", "w", "s", "e", "w", "n", "e", "n", "e", "e", "s", "e", "e", "e", "n", "e", "e", "n", "e", "s", "e", "s", "n", "w", "s", "n", "n", "e", "e", "e", "s", "s", "w", "e", "s", "w", "e", "n", "n", "n", "n", "e", "e", "s", "e", "s", "w", "w", "n", "s", "s", "s", "n", "n", "e", "s", "e", "e", "n", "s", "s", "w", "w", "e", "e", "e", "s", "n", "e", "n", "n", "n", "w", "s", "s", "n", "n", "e", "n", "w", "w", "w", "s", "w", "n", "w", "w", "s", "e", "s", "e", "e", "n", "n", "e", "e", "e", "e", "w", "s", "e", "e", "e", "n", "s", "w", "s", "s", "w", "w", "s", "s", "e", "n", "e", "e", "w", "s", "n", "n", "n", "n", "e", "n", "s", "w", "s", "e", "e", "n", "e", "n", "e", "e", "s", "w", "s", "w", "s", "n", "w", "w", "e", "w", "w", "s", "s", "s", "e", "e", "n", "n", "w", "e", "s", "s", "e", "n", "e", "n", "e", "e", "e", "e", "n", "w", "n", "w", "w", "w", "s", "e", "e", "w", "w", "n", "e", "e", "n", "s", "e", "n", "e", "w", "s", "e", "e", "n", "e", "e", "e", "e", "e", "s", "e", "n", "e", "s", "e", "s", "n", "n", "e", "s", "e", "s", "s", "e", "e", "e", "e", "e", "s", "w", "w", "s", "w", "s", "s", "w", "w", "e", "e", "n", "n", "w", "s", "w", "w", "s", "w", "n", "n", "e", "w", "n", "s", "w", "s", "s", "n", "w", "w", "e", "s", "w", "e", "n", "e", "n", "n", "w", "s", "w", "w", "n", "w", "w", "n", "e", "w", "s", "e", "s", "w", "s", "e", "w", "s", "e", "w", "n", "w", "w", "s", "n", "w", "w", "s", "e", "w", "n", "w", "s", "w", "e", "n", "n", "w", "w", "e", "s", "w", "s", "w", "w", "w", "n", "e", "e", "n", "n", "e", "e", "e", "e", "s", "e", "e", "e", "n", "n", "n", "e", "n", "e", "e", "s", "s", "e", "e", "e", "e", "e", "s", "e", "e", "e", "n", "w", "w", "n", "n", "n", "e", "e", "n", "w", "n", "w", "w", "w", "n", "n", "e", "e", "e", "n", "n", "n", "e", "n", "e", "s", "dismount", "e", "n", "ride", "e", "s", "e", "e", "e", "s", "s", "w", "w", "n", "w", "w", "w", "n", "n", "n", "w", "n", "w", "w", "n", "w", "w", "n", "w", "w", "n", "w", "n", "w", "w", "w", "n", "n", "n", "n", "s", "e", "e", "n", "w", "n", "w", "n", "n", "e", "n", "n", "w", "w", "n", "n", "n", "e", "e", "e", "e", "e", "n", "n", "e", "e", "n", "e", "n", "dismount", "od d", "od u", "ride", "s", "w", "s", "w", "w", "w", "w", "w", "w", "n", "w", "n", "s", "s", "s", "w", "w", "w", "n", "s", "s", "n", "e", "e", "e", "n", "n", "e", "s", "e", "e", "e", "e", "n", "n", "w", "s", "w", "w", "n", "n", "w", "w", "w", "s", "w", "w", "w", "w", "w", "n", "w"},
    mob_triggers = {
      { text = "A massive mirkwolf stares at you through blood red eyes.", attack = "massive" },
      { text = "A cave troll is standing here, pounding his two huge fists together.", attack = "troll" },
      { text = "A huge mirkwolf tenses its massive frame in readiness.", attack = "huge" },
      { text = "A hunched forest troll moves around here, arms dragging on the ground.", attack = "troll" },
      { text = "An evil, black warg paces around the clearing.", attack = "evil" },
      { text = "A malicious spider slides down its web with a look of hunger in its eyes.", attack = "malicious" },
      { text = "A trained warg waits here for an order from its master.", attack = "trained" },
      { text = "A large grizzly bear with golden fur stands here.", attack = "golden" },
      { text = "A blind spider hangs from a web here.", attack = "blind", hard = true },
      { text = "A spry spider weaves the cobwebs together as it scurries around the chamber.", attack = "spider" },
      { text = "A goblin hunter stands next to his kill, spear in hand.", attack = "goblin" },
      { text = "A trained warg waits here for an order from its masters.", attack = "trained" },
      { text = "A breeder assistant stands here trying to look busy.", attack = "breeder" },
      { text = "A huge troll, with a massive gut rests here, covered in oily black mud.", attack = "troll", hard = true },
      { text = "A large hunting spider carefully tests the air as it tracks its prey.", attack = "spider" },
      { text = "A fierce looking spider patrols its lair.", attack = "spider", hard = true },
      { text = "A twisted black spider is here waiting for dinner.", attack = "spider" },
      { text = "A black wolf wanders about, growling and frothing at the mouth.", attack = "wolf" },
      { text = "A black wolf looks at you and begins to growl.", attack = "wolf" },
      { text = "A shadowy spider sneaks through the darkness. (hiding)", attack = "shadowy" },
    },
  },
  spiderwebs = { title = "Spider Webs", start_room = "2518",
    commands = {"u", "w", "w", "w", "e", "e", "s", "w", "e", "n", "e", "d"},
    mob_triggers = {
      { text = "An ugly spider crouches in the shadows. (hiding)", attack = "spider" },
      { text = "A huge wolf spider is here hunting for prey.", attack = "spider" },
    },
  },
  thogs = { title = "Thogs",
    commands = {"e", "dismount", "u", "d", "ride", "s", "w", "w", "n", "dismount", "u", "d", "ride", "e", "s", "s", "dismount", "w", "s", "n", "e", "e", "s", "d", "n", "s", "u", "u", "n", "w", "#5 pick heavydoor", "w", "#5 pick heavydoor", "e", "s", "n", "e", "s", "d", "n", "w", "ride", "n", "n"},
    mob_triggers = {
      { text = "A deranged gatekeeper stands here guarding the gate.", attack = "gatekeeper" },
      { text = "A renegade soldier stands stands here.", attack = "renegade" },
      { text = "A renegade soldier is sleeping here upon his bunk.", attack = "renegade" },
      { text = "A watchtower guard stands here eyeing the surrounding forest.", attack = "guard" },
      { text = "A soldier is sitting around a large table here, laughing with his friends.", attack = "soldier" },
      { text = "The gaoler stands here, a low growl issuing from his throat.", attack = "gaoler" },
      { text = "An elite guardsman stands here, guarding his post.", attack = "guardsman" },
      { text = "Captain Lourdes looks up at you angrily as you enter.", attack = "Lourdes", hard = true },
      { text = "Thog Bloodsbane stands here, with a fiery light in his eyes.", attack = "Thog", hard = true },
    },
  },
  vegetation = { title = "Vegetation",
    commands = {"od d", "od e", "od w", "od u"},
    mob_triggers = {
      { text = "A large black snake is coiled up here, gazing at you intently.", attack = "snake" },
      { text = "A massive dark snake is coiled in the shadows here.", attack = "snake", hard = true },
    },
  },
  waterfall = { title = "Waterfall",
    commands = {"n", "n", "w", "w", "w", "w", "d", "e", "n", "w", "w", "w", "#5 pick skulls", "d", "#5 pick skulls", "u", "e", "e", "s", "u", "e", "e", "e", "e", "s", "s", "u"},
    mob_triggers = {
      { text = "A massive albino snake is here, flicking its white tongue.", attack = "snake" },
      { text = "A huge, bulky troll sits in the corner, slowly eating an old corpse.", attack = "troll", hard = true },
    },
  },
  wildtrolls = { title = "Wild Troll's Cave", start_room = "2377",
    commands = {"w", "n", "s", "e"},
    mob_triggers = {
      { text = "A large wild troll is here, green skinned and angry.", attack = "troll" },
      { text = "A cave troll is standing here, pounding his two huge fists together.", attack = "troll", hard = true },
    },
  },
}
